<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>Larpx.ResourceSpider.Enties</AssemblyName>
    <RootNamespace>Larpx.ResourceSpider.Enties</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="sqlSugarCore" Version="5.0.0.13" />
  </ItemGroup>

</Project>
