<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.1.165" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseLibrary\Larpx.ResourceSpider.BaseLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Downloader\" />
  </ItemGroup>

</Project>
