<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Larpx.ResourceSpider.Engine</AssemblyName>
    <RootNamespace>Larpx.ResourceSpider.Engine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="sqlSugarCore" Version="5.0.3.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseLibrary\Larpx.ResourceSpider.BaseLibrary.csproj" />
  </ItemGroup>

</Project>
