<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="sqlSugarCore" Version="5.0.0.15" />
    <PackageReference Include="System.Collections.Immutable" Version="1.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseLibrary\Larpx.ResourceSpider.BaseLibrary.csproj" />
    <ProjectReference Include="..\Larpx.ResourceSpider.Http\Larpx.ResourceSpider.Http.csproj" />
    <ProjectReference Include="..\Selector\Larpx.ResourceSpider.Selector.csproj" />
  </ItemGroup>

</Project>
