FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["src/ResourceSpider.Server/ResourceSpider.Server.csproj", "src/ResourceSpider.Server/"]
COPY ["src/ResourceSpider.Core/ResourceSpider.Core.csproj", "src/ResourceSpider.Core/"]
COPY ["src/ResourceSpider.Infrastructure/ResourceSpider.Infrastructure.csproj", "src/ResourceSpider.Infrastructure/"]
RUN dotnet restore "src/ResourceSpider.Server/ResourceSpider.Server.csproj"
COPY . .
WORKDIR "/src/src/ResourceSpider.Server"
RUN dotnet build "ResourceSpider.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ResourceSpider.Server.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ResourceSpider.Server.dll"]
