FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["src/ResourceSpider.Agent/ResourceSpider.Agent.csproj", "src/ResourceSpider.Agent/"]
COPY ["src/ResourceSpider.Core/ResourceSpider.Core.csproj", "src/ResourceSpider.Core/"]
COPY ["src/ResourceSpider.Infrastructure/ResourceSpider.Infrastructure.csproj", "src/ResourceSpider.Infrastructure/"]
RUN dotnet restore "src/ResourceSpider.Agent/ResourceSpider.Agent.csproj"
COPY . .
WORKDIR "/src/src/ResourceSpider.Agent"
RUN dotnet build "ResourceSpider.Agent.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ResourceSpider.Agent.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ResourceSpider.Agent.dll"]
