<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>Larpx.ResourceSpider.WebAPI</AssemblyName>
    <RootNamespace>Larpx.ResourceSpider.WebAPI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" Version="3.0.7" />
    <PackageReference Include="sqlSugarCore" Version="5.0.0.13" />
    <PackageReference Include="StackExchange.Redis" Version="2.1.30" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Enties\Enties.csproj" />
  </ItemGroup>


</Project>
