<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Larpx.ResourceSpider.Selector</AssemblyName>
    <RootNamespace>Larpx.ResourceSpider.Selector</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseLibrary\Larpx.ResourceSpider.BaseLibrary.csproj" />
  </ItemGroup>

</Project>
