<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>Larpx.ResourceSpider.Web</AssemblyName>
    <RootNamespace>Larpx.ResourceSpider.Web</RootNamespace>
    <UserSecretsId>666ca354-3186-46a0-971e-66aa3376f42e</UserSecretsId>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="sqlSugarCore" Version="5.0.0.13" />
  </ItemGroup>

</Project>
